version: '3'

services:
  {{ container }}:
    image: {{ image }}:{{ tag }}
    {% if ports is defined %}
    ports:
      - {{ ports }}
    {% endif %}

{% if airgradient_enable %}
{% for sensor in airgradient_sensors %}
  - job_name: 'airgradient-{{ sensor.id }}'
    metrics_path: /metrics
    scrape_interval: 30s
    static_configs:
      - targets: ['{{ sensor.ip }}:{{ sensor.port }}']
{% endfor %}
{% endif %}